CREATE TABLE USERS (ID VARCHAR(100) PRIMARY KEY, NAME VARCHAR(100) NOT NULL, PROFILE_IMAGE_URL BLOB);

CREATE TABLE BLOGS (ID INT AUTO_INCREMENT PRIMARY KEY, EMAIL VARCHAR(100) NOT NULL, PROFILE_IMAGE_URL VARCHAR(1000), USERNAME VARCHAR(100) NOT NULL, TITLE VARCHAR(1000) NOT NULL, SUBTITLE VARCHAR(1000), KEYWORDS VARCHAR(1000), POST_DATETIME DATETIME DEFAULT NOW() ON UPDATE NOW() NOT NULL, CONTENT LONGTEXT NOT NULL);

CREATE TABLE COMMENTS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(100) NOT NULL, POST_DATETIME DATETIME DEFAULT NOW() ON UPDATE NOW() NOT NULL, CONTENT TEXT NOT NULL, BLOG_ID INT NOT NULL, FOREIGN KEY (BLOG_ID) REFERENCES BLOGS(ID) ON DELETE CASCADE);